spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate
        properties.hibernate.hbm2ddl.auto: update

    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver